import fs from 'fs';
import path from 'path';

const sourceDir = 'hacked_prompts_source';
const outputFile = 'hacked_prompts.js';

async function main() {
    let output = `// This file is auto-generated by build_hacked_prompts.js\n// Do not edit this file directly. Edit the .txt files in ./${sourceDir}/\n\n`;

    try {
        const files = fs.readdirSync(sourceDir);

        for (const file of files) {
            if (path.extname(file) === '.txt') {
                const varName = path.basename(file, '.txt');
                const content = fs.readFileSync(path.join(sourceDir, file), 'utf8');
                
                // Use JSON.stringify to handle all escaping and wrap in quotes
                const escapedContent = JSON.stringify(content.trim(), null, 2);

                output += `// Prompt from ${file}\n`;
                output += `export const ${varName} = ${escapedContent};\n\n`;
            }
        }

        fs.writeFileSync(outputFile, output, 'utf8');
        console.log(`Successfully built ${outputFile} from ${sourceDir}/`);

    } catch (error) {
        console.error(`Error building ${outputFile}:`, error);
        process.exit(1);
    }
}

main();
