import { getCoreSystemPrompt, getCompressionPrompt } from './packages/core/dist/src/core/prompts.js';
import { SUMMARIZE_TOOL_OUTPUT_PROMPT } from './packages/core/dist/src/utils/summarizer.js';
import { EDIT_SYS_PROMPT, EDIT_USER_PROMPT } from './packages/core/dist/src/utils/llm-edit-fixer.js';
import fs from 'fs';
import path from 'path';

async function main() {
    const prompts = {
        EDIT_SYS_PROMPT: EDIT_SYS_PROMPT,
        EDIT_USER_PROMPT: EDIT_USER_PROMPT,
        SUMMARIZE_TOOL_OUTPUT_PROMPT: SUMMARIZE_TOOL_OUTPUT_PROMPT,
        COMPRESSION_PROMPT: getCompressionPrompt(),
        CORE_SYSTEM_PROMPT: getCoreSystemPrompt()
    };

    let output = `// This file is auto-generated by generate_prompts.js
// It contains the original prompts from the codebase and can be used as a template for hacked_prompts.js
// Using JSON.stringify for robust escaping.

`;

    for (const [key, value] of Object.entries(prompts)) {
        // We use JSON.stringify to handle all escaping of quotes, backslashes, newlines etc.
        // The second and third arguments pretty-print the string across multiple lines.
        output += `export const ${key} = ${JSON.stringify(value, null, 2)};

`;
    }

    const outputPath = path.join(process.cwd(), 'export_original_prompt.js');
    fs.writeFileSync(outputPath, output, 'utf8');
    console.log(`Successfully exported original prompts to: ${outputPath}`);
}

main().catch(console.error);
